# Generated by Django 4.2.7 on 2025-06-20 18:46

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_task_attachments_taskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.task_attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
