# Generated by Django 5.2.3 on 2025-06-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='currency',
            field=models.CharField(choices=[('INR', '₹ INR'), ('USD', '$ USD'), ('EUR', '€ EUR'), ('GBP', '£ GBP')], default='INR', max_length=3),
        ),
    ]
