# Generated by Django 5.2.3 on 2025-06-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_task_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_receipt',
            field=models.FileField(blank=True, help_text='Upload payment receipt', null=True, upload_to='payment_receipts/'),
        ),
    ]
