# Generated by Django 5.2.3 on 2025-06-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_payment_receipt'),
        ('accounts', '0008_invoice_payment_receipt'),
    ]

    operations = [
    ]
