# Generated by Django 5.2.3 on 2025-06-21 12:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20250621_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.invoice_receipt_upload_path),
        ),
    ]
